name: Python package

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9","3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd get-coinbase-reports
        python -m pip install venv lambda_venv
        source ./lambda_venv/bin/activate        
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        deactivate
        cd lambda_venv/lib/python3.12/site-packages
    - name: Package Lambda function
      run: |
        zip -r ../../../../my_deployment_package.zip .
     #   zip -r lambda_function.zip . -x "venv/*"
        
        
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to AWS
      run: |
        

