name: Python package

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m venv lambda_env
        source lambda_env/bin/activate
        cd get-coinbase-reports
        pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        deactivate
    - name: Package Lambda function
      run: |
        zip -r lambda_function.zip lambda_env/ your_lambda_function.py
#        zip -r lambda_function.zip . -x "venv/*"
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"
    - name: Deploy to AWS
      run: |
        aws lambda update-function-code --function-name coinbase-brassert-report --zip-file fileb://lambda_function.zip


    
   
